# Change these first
owner: Constrix # Your GitHub organization or username, where this repository lives
repo: Constrix-upptime # The name of this repository

sites:
  - name: constrix.org (Constrix Official Website)
    url: constrix.org
  - name: cs.constrix:27015 (Constrix Cs 1.6 Game Server)
    url: cs.constrix.org:27015
  - name: forum.constrix.org (Constrix Forum)
    url: forum.constrix.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.constrix.org
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/138226524?s=200&v=4
  name: Constrix - Status page
  introTitle: "**Constrix** status page"
  introMessage: Here is a status page for Constrix. with uptime response time information.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  favicon: https://avatars.githubusercontent.com/u/138226524?s=200&v=4

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration